'use client';

import { useState, useRef, useEffect } from 'react';
import {
  X, FileText, Download, Sparkles, BarChart3, Mail,
  Search, Grid, Plus, Check, Play, FileSpreadsheet,
  ChevronRight, ArrowRight, ShieldCheck, Terminal, HelpCircle
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';
import { type CanvasData, type CanvasType } from './CanvasPanel';

interface ArtifactsGalleryPanelProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectArtifact: (data: CanvasData) => void;
  isSidebarCollapsed?: boolean;
  messages?: any[];
}

// Monochromatic document items
interface MockArtifact {
  id: string;
  type: CanvasType;
  tag: string;
  title: string;
  subtitle: string;
  time: string;
  content: any;
  raw: string;
  isCustom?: boolean;
}

export function ArtifactsGalleryPanel({
  isOpen,
  onClose,
  onSelectArtifact,
  isSidebarCollapsed,
  messages = []
}: ArtifactsGalleryPanelProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [width, setWidth] = useState(540);
  const [isResizing, setIsResizing] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  // ─── Resize Handlers ─────────────────────────────────────────────────────────
  const startResizing = (e: React.MouseEvent) => {
    e.preventDefault();
    setIsResizing(true);
  };

  const stopResizing = () => {
    setIsResizing(false);
  };

  const handleResize = (e: MouseEvent) => {
    if (!isResizing || window.innerWidth < 768) return;
    const sidebarW = isSidebarCollapsed ? 80 : 256;
    const max = window.innerWidth - sidebarW - 500 - 48;
    const next = window.innerWidth - e.clientX;
    setWidth(Math.max(380, Math.min(next, max)));
  };

  useEffect(() => {
    window.addEventListener('mousemove', handleResize);
    window.addEventListener('mouseup', stopResizing);
    return () => {
      window.removeEventListener('mousemove', handleResize);
      window.removeEventListener('mouseup', stopResizing);
    };
  }, [isResizing, isSidebarCollapsed]);

  // ─── Dynamic session artifacts extraction ──────────────────────────────────
  const dynamicArtifacts: MockArtifact[] = [];
  messages.forEach((msg, index) => {
    if (msg.role === 'assistant' && msg.meta) {
      if (msg.meta.planArtifact) {
        const plan = msg.meta.planArtifact;
        dynamicArtifacts.push({
          id: `dyn-plan-${index}`,
          type: 'action_plan',
          tag: 'Action Plan · MD',
          title: plan.title || 'Strategic Mission Plan',
          subtitle: `Extracted from chat session`,
          time: msg.time || 'Just now',
          content: plan,
          raw: `# ${plan.title || 'Strategic Mission Plan'}\n\nObjective: ${plan.objective || 'N/A'}\n\n${plan.steps?.map((s: any, idx: number) => `### Step ${idx + 1}: ${s.action}\n${s.description}\n`).join('\n') || ''}`
        });
      }
      if (msg.meta.canvasApproval?.canvasData) {
        const cv = msg.meta.canvasApproval.canvasData;
        dynamicArtifacts.push({
          id: `dyn-appr-${index}`,
          type: cv.type || 'workflow',
          tag: 'Mission Spec · JSON',
          title: msg.meta.canvasApproval.title || 'Canvas Workflow Specification',
          subtitle: `Extracted from chat session`,
          time: msg.time || 'Just now',
          content: cv.content,
          raw: cv.raw || JSON.stringify(cv.content, null, 2)
        });
      }
      if (msg.meta.result?.canvasData) {
        const cv = msg.meta.result.canvasData;
        dynamicArtifacts.push({
          id: `dyn-res-${index}`,
          type: cv.type || 'notes',
          tag: 'Result Artifact · MD',
          title: msg.meta.result.title || 'Action Results Summary',
          subtitle: `Extracted from chat session`,
          time: msg.time || 'Just now',
          content: cv.content,
          raw: cv.raw || (typeof cv.content === 'string' ? cv.content : JSON.stringify(cv.content, null, 2))
        });
      }
    }
  });

  // ─── Default beautiful monochromatic documents ─────────────────────────────
  const defaultArtifacts: MockArtifact[] = [
    {
      id: 'doc-roadmap',
      type: 'report',
      tag: 'Document · MD',
      title: 'Q3 Product Roadmap & Strategic Milestones',
      subtitle: 'Generated by Arcus',
      time: '2h ago',
      content: {},
      raw: `# Q3 Product Roadmap & Strategic Milestones\n\n### Executive Summary\nThis document outlines our core focus areas, feature timelines, and engineering milestones for the third quarter of 2026.\n\n---\n\n### 1. Unified Integration Framework (UIF)\n- **Timeline:** July 1 - July 25\n- **Objective:** Enable one-click zero-config synchronization for all third-party developer integrations.\n- **Status:** ◆ Active Development\n\n### 2. High-Performance Sift Intelligence\n- **Timeline:** July 20 - August 15\n- **Objective:** Optimize prompt size constraints to eliminate 504 Gateway Timeouts on deep inbox triage operations.\n- **Status:** ◆ Optimization Phase\n\n### 3. Arcus Autonomous Action Loops\n- **Timeline:** August 10 - September 20\n- **Objective:** Deploy context-aware SSE execution trees supporting nested workflows.\n- **Status:** ⏳ Scheduled\n\n---\n\n> [!NOTE]\n> Deliverables are subject to standard quality assurance checks. Product priorities will adjust based on customer demand telemetry.`
    },
    {
      id: 'doc-deck',
      type: 'notes',
      tag: 'Presentation · PPTX',
      title: 'Arcus AI: Premium Enterprise Intelligence Pitch Deck',
      subtitle: 'Generated by Arcus',
      time: '5h ago',
      content: {},
      raw: `# Arcus AI: Premium Enterprise Intelligence\n\n---\n\n## Slide 1: Executive Thesis\n- **The Problem:** Modern teams drown in asynchronous email chaos, fragmented SaaS integrations, and disjointed schedules.\n- **The Solution:** Arcus provides an elegant, monochromatic, context-aware command center that triages, plans, and executes.\n\n---\n\n## Slide 2: Market Pull & Traction\n- **Mailient Core Engine:** Triaging over 20,000 corporate threads daily.\n- **Notion & Slack MCP Nodes:** Deployed in 300+ beta organizations with zero downtime.\n- **Revenue Projections:** Fast-pathing ARR through high-impact corporate tiers.\n\n---\n\n## Slide 3: Pure Black & White Premium Architecture\n- **Monochromatic Glassmorphism:** Designed for extreme visual clarity and distraction-free decision making.\n- **Execution Gateway:** Secure token handshakes across Gmail, Notion, Slack, and Google Calendar.`
    },
    {
      id: 'doc-sheets',
      type: 'analytics',
      tag: 'Spreadsheet · XLSX',
      title: 'Financial Model & Revenue Growth Trajectory',
      subtitle: 'Generated by Arcus',
      time: 'Yesterday',
      content: {},
      raw: `# Financial Model & Revenue Growth Trajectory\n\nHere is the detailed quarterly financial projection for our premium subscription pipelines:\n\n\`\`\`chart\ntype: bar\ntitle: Revenue Trajectory (USD)\nlabels: ["Q1 Proj", "Q2 Proj", "Q3 Proj", "Q4 Proj"]\ndata: [120000, 240000, 480000, 960000]\n\`\`\`\n\n### Key Metrics Table\n| Quarter | Projected Subscribers | Operating Costs | Gross Revenue | Growth Rate |\n| :--- | :--- | :--- | :--- | :--- |\n| Q1 Proj | 1,200 | $35,000 | $120,000 | Baseline |\n| Q2 Proj | 2,400 | $48,000 | $240,000 | +100% |\n| Q3 Proj | 4,800 | $65,000 | $480,000 | +100% |\n| Q4 Proj | 9,600 | $90,000 | $960,000 | +100% |\n\n---\n\n> [!TIP]\n> Projections are modeled on current conversion metrics from waitlisted domains (approx. 4.8%).`
    },
    {
      id: 'doc-brief',
      type: 'summary',
      tag: 'Document · DOCX',
      title: 'Executive Triage Briefing: Customer Acquisition Pipeline',
      subtitle: 'Generated by Arcus',
      time: '2 days ago',
      content: {},
      raw: `# Executive Triage Briefing: Customer Acquisition Pipeline\n\n### 1. Context Assessment\nArcus analyzed incoming enterprise inquiries from the last 48 hours to identify high-revenue opportunities.\n\n### 2. High-Value Leads Identified\n- **Domain:** Acme Corp (VP Product)\n  - **Insight:** Seeking Notion MCP syncing for 500+ seat organization.\n  - **Suggested Action:** Auto-draft high-priority enterprise contract proposal.\n- **Domain:** Global Logistics Ltd (COO)\n  - **Insight:** Requires custom Slack trigger pipelines for delivery exceptions.\n  - **Suggested Action:** Initiate workflow builder in Canvas.`
    }
  ];

  // Combine dynamic artifacts first, followed by default ones
  const allArtifacts = [...dynamicArtifacts, ...defaultArtifacts];

  // Filter based on search query
  const filteredArtifacts = allArtifacts.filter(art =>
    art.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
    art.tag.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleDownload = (e: React.MouseEvent, art: MockArtifact) => {
    e.stopPropagation();
    try {
      const blob = new Blob([art.raw], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${art.title.replace(/\s+/g, '_').toLowerCase()}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      toast.success('File download initiated successfully');
    } catch (err) {
      toast.error('Could not download file');
    }
  };

  const handleSelect = (art: MockArtifact) => {
    const data: CanvasData = {
      type: art.type,
      title: art.title,
      content: art.content,
      raw: art.raw
    };
    onSelectArtifact(data);
    toast.success(`Opening "${art.title}" in Canvas`);
  };

  const panelWidth = window.innerWidth < 768 ? 'calc(100vw - 24px)' : `${width}px`;

  return (
    <div
      className={cn(
        'h-[calc(100vh-32px)] flex flex-col flex-shrink-0 relative bg-black border-l border-white/[0.08] shadow-2xl rounded-r-[32px] overflow-hidden'
      )}
      style={{ width: panelWidth }}
      ref={scrollRef}
    >
      {/* Premium Grain Overlay */}
      <div className="absolute inset-0 pointer-events-none opacity-[0.02] z-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] brightness-100 contrast-150" />

      {/* Resize Handle (Left side border) */}
      <div
        onMouseDown={startResizing}
        className="absolute left-0 top-0 bottom-0 w-1.5 cursor-col-resize z-[100] group/resize hover:bg-white/10 transition-colors"
      >
        <div className="absolute left-[2px] top-1/2 -translate-y-1/2 w-[2px] h-8 rounded-full bg-white/10 group-hover/resize:bg-white/30 transition-colors" />
      </div>

      {/* Header section */}
      <div className="px-6 py-5 border-b border-white/[0.08] flex items-center justify-between shrink-0 relative z-10">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-xl bg-white/[0.04] border border-white/[0.08] flex items-center justify-center">
            <FileText className="w-4 h-4 text-white/80" />
          </div>
          <div>
            <h3 className="text-[14px] font-bold text-white tracking-tight lowercase">Documents & Artifacts</h3>
            <p className="text-[10px] text-white/40 tracking-tight uppercase">Your workspace library</p>
          </div>
        </div>

        <button
          onClick={onClose}
          className="p-2 hover:bg-white/[0.06] rounded-xl transition-all text-white/40 hover:text-white"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Search Input */}
      <div className="px-6 py-4 border-b border-white/[0.04] shrink-0 relative z-10">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/30" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search documents, sheets, templates..."
            className="w-full pl-9 pr-4 py-2 bg-white/[0.03] border border-white/[0.06] rounded-xl text-[13px] text-white placeholder:text-white/20 focus:outline-none focus:border-white/20 transition-all font-medium tracking-tight"
          />
        </div>
      </div>

      {/* Scrollable Gallery Content */}
      <div className="flex-1 overflow-y-auto px-6 py-6 space-y-8 relative z-10 select-none scrollbar-thin scrollbar-thumb-white/10">
        
        {/* TOP SECTION: Horizontal Scrollable List */}
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <h4 className="text-[11px] font-bold text-white/40 uppercase tracking-wider">Recent Documents</h4>
            <span className="text-[10px] text-white/30 font-mono">{filteredArtifacts.length} total</span>
          </div>

          {/* Horizontal Scroller */}
          <div className="flex gap-4 overflow-x-auto pb-4 -mx-6 px-6 scrollbar-thin scrollbar-thumb-white/5 scroll-smooth">
            {filteredArtifacts.map((art) => {
              const isPresentation = art.tag.includes('Presentation');
              const isSpreadsheet = art.tag.includes('Spreadsheet');

              return (
                <div
                  key={art.id}
                  onClick={() => handleSelect(art)}
                  className="flex-shrink-0 w-[240px] p-4 bg-white/[0.02] hover:bg-white/[0.05] border border-white/[0.06] hover:border-white/20 rounded-2xl transition-all duration-300 ease-out cursor-pointer relative group flex flex-col justify-between h-[160px] shadow-lg"
                >
                  <div>
                    {/* Badge and Download Button */}
                    <div className="flex items-center justify-between mb-3.5">
                      <span className="px-2 py-0.5 rounded-full bg-white/[0.04] border border-white/[0.06] text-[9px] font-mono text-white/80">
                        {art.tag}
                      </span>
                      <button
                        onClick={(e) => handleDownload(e, art)}
                        className="p-1.5 hover:bg-white/10 rounded-lg transition-colors text-white/40 hover:text-white opacity-0 group-hover:opacity-100"
                        title="Download Raw Source"
                      >
                        <Download className="w-3.5 h-3.5" />
                      </button>
                    </div>

                    {/* Title */}
                    <h5 className="text-[12.5px] font-bold text-white leading-snug line-clamp-2 tracking-tight">
                      {art.title}
                    </h5>
                  </div>

                  {/* Subtitle / Footer */}
                  <div className="flex items-center justify-between mt-4 pt-3 border-t border-white/[0.04] text-[10px] text-white/40">
                    <span>{art.subtitle}</span>
                    <span>{art.time}</span>
                  </div>
                </div>
              );
            })}

            {filteredArtifacts.length === 0 && (
              <div className="w-full py-12 flex flex-col items-center justify-center text-center px-4">
                <FileText className="w-8 h-8 text-white/10 mb-3" />
                <p className="text-[12px] text-white/30 font-medium">No recent documents matching query</p>
              </div>
            )}
          </div>
        </div>

        {/* BOTTOM SECTION: Content Previews & Grid */}
        <div className="space-y-4">
          <div className="flex items-center justify-between pb-1 border-b border-white/[0.06]">
            <h4 className="text-[11px] font-bold text-white/80 uppercase tracking-wider">Content & Previews</h4>
            <span className="text-[10px] text-white/40 uppercase tracking-wider font-mono">Monochromatic System</span>
          </div>

          {/* Grid Layout of diverse artifacts */}
          <div className="grid grid-cols-1 gap-4">
            
            {/* Monochromatic Analytics Preview Card */}
            <div
              onClick={() => handleSelect(allArtifacts.find(a => a.id === 'doc-sheets') || allArtifacts[2])}
              className="group p-5 bg-white/[0.02] hover:bg-white/[0.05] border border-white/[0.06] hover:border-white/20 rounded-2xl transition-all duration-300 ease-out cursor-pointer relative overflow-hidden"
            >
              <div className="flex items-start justify-between mb-4">
                <div>
                  <span className="px-2 py-0.5 rounded-full bg-white/[0.04] border border-white/[0.06] text-[9px] font-mono text-white/80">
                    Analytics · Interactive Chart
                  </span>
                  <h5 className="text-[13px] font-bold text-white tracking-tight mt-2">Revenue Growth & Quarterly Performance</h5>
                </div>
                <div className="p-2 bg-white/[0.04] border border-white/[0.06] rounded-xl">
                  <BarChart3 className="w-4 h-4 text-white/60" />
                </div>
              </div>

              {/* Minimalist Monochromatic Chart Wireframe */}
              <div className="h-28 flex items-end justify-between gap-2.5 bg-black/40 border border-white/[0.04] rounded-xl p-4 relative">
                <div className="absolute inset-0 bg-gradient-to-t from-white/[0.01] to-transparent pointer-events-none" />
                
                {/* Visualizing 4 bars with varying levels of white/gray opacities */}
                <div className="flex-1 flex flex-col items-center justify-end h-full">
                  <motion.div initial={{ height: 0 }} animate={{ height: '30%' }} transition={{ duration: 0.8 }} className="w-full bg-white/20 rounded-t-sm" />
                  <span className="text-[8px] text-white/30 font-mono mt-1">Q1</span>
                </div>
                <div className="flex-1 flex flex-col items-center justify-end h-full">
                  <motion.div initial={{ height: 0 }} animate={{ height: '50%' }} transition={{ duration: 0.8, delay: 0.1 }} className="w-full bg-white/40 rounded-t-sm" />
                  <span className="text-[8px] text-white/30 font-mono mt-1">Q2</span>
                </div>
                <div className="flex-1 flex flex-col items-center justify-end h-full">
                  <motion.div initial={{ height: 0 }} animate={{ height: '70%' }} transition={{ duration: 0.8, delay: 0.2 }} className="w-full bg-white/60 rounded-t-sm" />
                  <span className="text-[8px] text-white/30 font-mono mt-1">Q3</span>
                </div>
                <div className="flex-1 flex flex-col items-center justify-end h-full">
                  <motion.div initial={{ height: 0 }} animate={{ height: '95%' }} transition={{ duration: 0.8, delay: 0.3 }} className="w-full bg-white rounded-t-sm" />
                  <span className="text-[8px] text-white/30 font-mono mt-1">Q4</span>
                </div>
              </div>

              <div className="flex items-center justify-between mt-3 text-[10px] text-white/40 font-mono">
                <span>Projection Model v1.2</span>
                <span className="flex items-center gap-1">Open in Canvas <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" /></span>
              </div>
            </div>

            {/* Structured Email Draft Card */}
            <div
              onClick={() => handleSelect(allArtifacts.find(a => a.id === 'doc-brief') || allArtifacts[3])}
              className="group p-5 bg-white/[0.02] hover:bg-white/[0.05] border border-white/[0.06] hover:border-white/20 rounded-2xl transition-all duration-300 ease-out cursor-pointer relative"
            >
              <div className="flex items-start justify-between mb-4">
                <div>
                  <span className="px-2 py-0.5 rounded-full bg-white/[0.04] border border-white/[0.06] text-[9px] font-mono text-white/80">
                    Draft · Business Proposals
                  </span>
                  <h5 className="text-[13px] font-bold text-white tracking-tight mt-2">Executive Briefing & Strategic Inbound Proposals</h5>
                </div>
                <div className="p-2 bg-white/[0.04] border border-white/[0.06] rounded-xl">
                  <Mail className="w-4 h-4 text-white/60" />
                </div>
              </div>

              {/* Monochromatic Structured Preview */}
              <div className="space-y-2 p-3 bg-black/40 border border-white/[0.04] rounded-xl text-[11px] font-mono text-white/50">
                <div className="flex justify-between border-b border-white/[0.04] pb-1">
                  <span>To: partner@ventureholdings.com</span>
                  <span>Priority: High</span>
                </div>
                <div className="border-b border-white/[0.04] pb-1">
                  <span>Subject: Mailient Seed Financing Term Sheet Confirmation</span>
                </div>
                <div className="line-clamp-2 pt-1">
                  Dear Venture Team, Arcus has completed the analysis on waitlist traction and waitlisted domains. We have attached the...
                </div>
              </div>

              <div className="flex items-center justify-between mt-3 text-[10px] text-white/40">
                <span>Auto-drafted by Arcus loop</span>
                <span className="flex items-center gap-1 font-mono">Open in Canvas <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" /></span>
              </div>
            </div>

            {/* Custom Monochromatic Wireframe / Image Placeholder Grid */}
            <div className="grid grid-cols-2 gap-4">
              
              <div
                onClick={() => handleSelect(allArtifacts.find(a => a.id === 'doc-roadmap') || allArtifacts[0])}
                className="group p-4 bg-white/[0.02] hover:bg-white/[0.05] border border-white/[0.06] hover:border-white/20 rounded-2xl transition-all duration-300 ease-out cursor-pointer flex flex-col justify-between h-[150px]"
              >
                <div className="space-y-2">
                  <div className="w-8 h-8 rounded-lg bg-white/[0.04] border border-white/[0.08] flex items-center justify-center">
                    <Terminal className="w-4 h-4 text-white/80" />
                  </div>
                  <h5 className="text-[12px] font-bold text-white tracking-tight line-clamp-2">Product Milestones & Roadmap</h5>
                </div>
                
                <span className="text-[9px] text-white/40 uppercase tracking-widest font-mono">Markdown (MD)</span>
              </div>

              <div
                onClick={() => handleSelect(allArtifacts.find(a => a.id === 'doc-deck') || allArtifacts[1])}
                className="group p-4 bg-white/[0.02] hover:bg-white/[0.05] border border-white/[0.06] hover:border-white/20 rounded-2xl transition-all duration-300 ease-out cursor-pointer flex flex-col justify-between h-[150px]"
              >
                <div className="space-y-2">
                  <div className="w-8 h-8 rounded-lg bg-white/[0.04] border border-white/[0.08] flex items-center justify-center">
                    <HelpCircle className="w-4 h-4 text-white/80" />
                  </div>
                  <h5 className="text-[12px] font-bold text-white tracking-tight line-clamp-2">Premium Deck Presentation</h5>
                </div>
                
                <span className="text-[9px] text-white/40 uppercase tracking-widest font-mono">Slides (PPTX)</span>
              </div>

            </div>

          </div>
        </div>

      </div>
    </div>
  );
}
